font:
    normal:
        family: Hack Nerd Font
        style: Regular
    bold:
        family: Hack Nerd Font
        style: Bold
    size: 14
mouse:
    hide_when_typing: true

key_bindings:
    - { key: N, mods: Control|Shift, action: SpawnNewInstance }
