[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control|Shift"

[env]
COLORTERM = "truecolor"

[font]
size = 14.5

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
y = 4

[mouse]
hide_when_typing = true

[scrolling]
history = 0
multiplier = 0

# Atom One Dark
[colors.primary]
background = "#282c34"
foreground = "#abb2bf"

[colors.cursor]
text = "#282c34"
cursor = "#abb2bf"

[colors.normal]
black = "#282c34"
red = "#e06c75"
green = "#98c379"
yellow = "#e5c07b"
blue = "#61afef"
magenta = "#c678dd"
cyan = "#56b6c2"
white = "#abb2bf"

[colors.bright]
black = "#3e4451"
red = "#be5046"
green = "#98c379"
yellow = "#d19a66"
blue = "#61afef"
magenta = "#c678dd"
cyan = "#56b6c2"
white = "#c8ccd4"
