#!/usr/bin/env bash

CHECKOUT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
BASE_16_URI='https://github.com/chriskempson/base16-shell'

# Remove old
rm -rf base16-shell
rm -rf ~/.fzf*
rm -rf ~/.nvm
rm -rf ~/.volta
rm -f ~/.config/nvim
rm -rf ~/.local/share/nvim

# Terminal Configuration
ln -sf $CHECKOUT_PATH/alacritty.yml ~/.alacritty.yml

# Base 16 Theming
git clone $BASE_16_URI
ln -sf $CHECKOUT_PATH/base16-shell/scripts ~/.base16_themes

# Tmux Configuration
ln -sf $CHECKOUT_PATH/tmux.conf ~/.tmux.conf

# Bash Configuration
if [ "$(uname)" == "Darwin" ]; then
    cp $CHECKOUT_PATH/bashrc_osx ~/.bashrc
    echo -e "\n. $CHECKOUT_PATH/bashrc" >> ~/.bashrc
    echo "[ -f $(brew --prefix)/etc/bash_completion ] && . $(brew --prefix)/etc/bash_completion" > ~/.bash_profile
    echo "[ -f "$HOME/.bashrc" ] && . $HOME/.bashrc" >> ~/.bash_profile
    ln -sf $CHECKOUT_PATH/tmux_osx.conf ~/.tmux_osx.conf
else
    ln -sf $CHECKOUT_PATH/bashrc ~/.bashrc
fi

# FZF
git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
~/.fzf/install --completion --key-bindings --no-update-rc --no-zsh --no-fish

# Volta & Node
curl https://get.volta.sh | bash -s -- --skip-setup
PATH="$HOME/.volta/bin:$PATH"
volta install node

npm install -g neovim
# Required for https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#tsserver
npm install -g typescript typescript-language-server
# Required for https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#eslint and
# https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#cssls and
# https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#html
npm install -g vscode-langservers-extracted
# Required for CLI utility and https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#angularls
npm install -g @angular/cli@$ng_version @angular/language-server@$ng_version

# Vim Configuration
mkdir -p ~/.config
ln -sf $CHECKOUT_PATH/nvim ~/.config/nvim
