#!/usr/bin/env bash

pushd `dirname $0` > /dev/null
CHECKOUT_PATH=`pwd`
popd > /dev/null

BASE_16_URI='https://raw.githubusercontent.com/chriskempson/base16-shell/master'
BASE_16_THEME='ocean'

ln -sf $CHECKOUT_PATH/bashrc ~/.bashrc
ln -sf $CHECKOUT_PATH/tmux.conf ~/.tmux.conf

wget $BASE_16_URI/base16-$BASE_16_THEME.dark.sh -O ~/.shell_theme.sh

mkdir -p ~/.config
mkdir -p ~/.vim
ln -sf $CHECKOUT_PATH/vimrc ~/.vimrc
ln -sf ~/.vim ~/.config/nvim
ln -sf $CHECKOUT_PATH/vimrc ~/.config/nvim/init.vim

if [ "$(uname)" == "Darwin" ]; then
    ln -sf $CHECKOUT_PATH/bash_profile_osx ~/.bash_profile
    ln -sf $CHECKOUT_PATH/tmux_osx.conf ~/.tmux_osx.conf
fi
