require('packer-init')

require('core.base')
require('core.mappings')

require('plugins.nvim-treesitter')
require('plugins.onedark')
require('plugins.lualine')
require('plugins.bufferline')
require('plugins.nvim-tree')
require('plugins.gitsigns')
require('plugins.indent-blankline')
require('plugins.nvim-notify')
require('plugins.fzf')
require('plugins.hop')
require('plugins.fugitive')
require('plugins.nvim-tmux-navigation')
require('plugins.nvim-comment')
require('plugins.nvim-surround')
require('plugins.nvim-autopairs')
require('plugins.mason')

require('plugins.completion')
